"""initial migration

Revision ID: fc5d23b450c9
Revises: 
Create Date: 2025-06-11 14:23:14.805562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5d23b450c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET is_active = TRUE')
    op.alter_column('users', 'is_active', nullable=False)
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET is_superuser = TRUE')
    op.alter_column('users', 'is_superuser', nullable=False)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET is_verified = TRUE')
    op.alter_column('users', 'is_verified', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
