name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run flake8
        run: |
          flake8 src --max-line-length=120 --statistics

      - name: Run pytest
        run: |
          pytest tests --disable-warnings --maxfail=1

      - name: Build Docker image
        run: |
          docker build -t new-api-project-api:latest src/
